# this configuration file has all empty custom components set up.
# use 'esphome test_empty.yaml compile' to build. 

packages:
  device: !include device.yaml # include our test device setup

external_components:
  - source:
      type: local
      path: components

balboa_spa:
  id: test_spa

uart:
  tx_pin: D0
  rx_pin: D1
  baud_rate: 9600

binary_sensor:
  - platform: balboa_spa
    balboa_spa_id: test_spa
    jet1:
      id: jet1
    jet2:
      id: jet2
    lights:
      id: lights


climate:
  - platform: balboa_spa
    balboa_spa_id: test_spa
